router:
  image: nginx:latest
  links:
  - web
  ports:
  - "443:443"
  volumes:
  - ./router/snakeoil.key:/etc/ssl/snakeoil.key:ro
  - ./router/snakeoil.crt:/etc/ssl/snakeoil.crt:ro
  - ./router/nginx.conf:/etc/nginx/nginx.conf:ro
web:
  image: nginx:latest
  links:
  - auth-web
  volumes:
  - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
  - ./web/app:/www:ro
  - ./auth-service/web/auth-service.include:/etc/nginx/auth-service.include:ro
database:
  image: postgres:9.4.0
server:
  build: server
  links:
  - database
auth-service:
  build: auth-service
  links:
  - database
auth-web:
  build: auth-service/web
  links:
  - auth-service
  - server:c1a1501b-f0af-4c2e-b925-a2aad7b61335