router:
  image: nginx:latest
  links:
  - web
  ports:
  - "443:443"
  volumes:
  - ./router/snakeoil.key:/etc/ssl/tranarappen.key:ro
  - ./router/snakeoil.crt:/etc/ssl/tranarappen.crt:ro
  - ./router/nginx.conf:/etc/nginx/nginx.conf:ro
web:
  image: nginx:latest
  links:
  - authweb
  volumes:
  - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
  - ./web/app:/www:ro
  - ./auth-service/web/auth-service.include:/etc/nginx/auth-service.include:ro
database:
  image: postgres:9.4
  ports:
  - "5432:5432"
server:
  build: server
  links:
  - database
authservice:
  build: auth-service
  links:
  - database
authweb:
  build: auth-service/web
  links:
  - authservice
  - server:c1a1501b-f0af-4c2e-b925-a2aad7b61335
