web:
  build: web
  links:
  - server
  ports:
  - "443:443"
  volumes:
  - ./web/app:/usr/share/nginx/html:ro
database:
  image: postgres:9.4
  ports:
  - "5432:5432"
server:
  build: server
  links:
  - database